# -*- coding: utf-8 -*-
"""hw2-semantic_segmentation-Vayser_Kirill-attempt-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SjQ-VjY42oOOH704piB3npYSXJ2VTN9S

# Homework 3. Dense Prediction (50 points)
---
In this part, you will study a problem of segmentation. The goal of this assignment is to study, implement, and compare different components of dense prediction models, including **data augmentation**, **backbones**, **classifiers** and **losses**.

This assignment will require training multiple neural networks, therefore it is advised to use a **GPU** accelerator.

<font color='red'>**In this task, it is obligatory to provide accuracy plots on the training and validation datasets obtained during training, as well as examples of the work of each of the models on the images. Without plots, your work will get 0 points. Writing a report is just as important as writing code.**</font>

**<font color='red'>Before the submission please convert your notebook to .py file and check that it runs correctly. How to get .py file in Colab: File -> Download -> Download .py**
"""

# !pip install -U gdown
# !pip install pytorch_lightning
# !pip uninstall opencv-python-headless 
# !pip install opencv-python-headless==4.1.2.30
# !pip install git+https://github.com/albumentations-team/albumentations

# Determine the locations of auxiliary libraries and datasets.
# `AUX_DATA_ROOT` is where 'tiny-imagenet-2022.zip' is.

# Detect if we are in Google Colaboratory
try:
    import google.colab
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

from pathlib import Path
if IN_COLAB:
    google.colab.drive.mount("/content/drive")
    
    # Change this if you created the shortcut in a different location
    AUX_DATA_ROOT = Path("/content/drive/My Drive/Skoltech/DL/HW2/HW2")
    
    assert AUX_DATA_ROOT.is_dir(), "Have you forgot to 'Add a shortcut to Drive'?"
    
    import sys
    sys.path.append(str(AUX_DATA_ROOT))
else:
    AUX_DATA_ROOT = Path(".")

AUX_DATA_ROOT

# pass a python variable to console in brckets {}
# !ls {'"%s"' % AUX_DATA_ROOT}

# Uncomment and run if in Colab
# !mkdir datasets
# !cp '{AUX_DATA_ROOT}/tiny-floodnet-challenge.tar.gz' datasets/tiny-floodnet-challenge.tar.gz
# !tar -xzf datasets/tiny-floodnet-challenge.tar.gz -C datasets
# !rm datasets/tiny-floodnet-challenge.tar.gz

# !ls datasets/tiny-floodnet-challenge

"""## Dataset

We will use a simplified version of a [FloodNet Challenge](http://www.classic.grss-ieee.org/earthvision2021/challenge.html).

Compared to the original challenge, our version doesn't have difficult (and rare) "flooded" labels, and the images are downsampled

<img src="https://i.imgur.com/RZuVuVp.png" />

## Assignments and grading


- **Part 1. Code**: fill in the empty gaps (marked with `#TODO`) in the code of the assignment (34 points):
    - `dataset` -- 4 points
    - `model` -- 20 points
    - `loss` -- 8 points
    - `train` -- 2 points
- **Part 2. Train and benchmark** the performance of the required models (6 points):
    - All 6 checkpoints are provided -- 3 points
    - Checkpoints have > 0.5 accuracy -- 3 points
- **Part 3. Report** your findings (10 points)
    - Each task -- 2.5 points

- **Total score**: 50 points.

For detailed grading of each coding assignment, please refer to the comments inside the files. Please use the materials provided during a seminar and during a lecture to do a coding part, as this will help you to further familiarize yourself with PyTorch. Copy-pasting the code from Google Search will get penalized.

In part 2, you should upload all your pre-trained checkpoints to your personal Google Drive, grant public access and provide a file ID, following the intructions in the notebook.

Note that for each task in part 3 to count towards your final grade, you should complete the corresponding tasks in part 2.

For example, if you are asked to compare Model X and Model Y, you should provide the checkpoints for these models in your submission, and their accuracies should be above minimal threshold.

## Part 1. Code

### `dataset`
**TODO: implement and apply data augmentations**

You'll need to study a popular augmentations library: [Albumentations](https://albumentations.ai/), and implement the requested augs. Remember that geometric augmentations need to be applied to both images and masks at the same time, and Albumentations has [native support](https://albumentations.ai/docs/getting_started/mask_augmentation/) for that.
"""

from torch.utils.data import Dataset, DataLoader
import albumentations as A
from torchvision.transforms import ToTensor
import os
from PIL import Image
import numpy as np
import torch



class FloodNet(Dataset):
    """
    Labels semantic:
    0: Background, 1: Building, 2: Road, 3: Water, 4: Tree, 5: Vehicle, 6: Pool, 7: Grass
    """
    def __init__(
        self,
        data_path: str,
        phase: str,
        augment: bool,
        img_size: int,
    ):
        self.num_classes = 8
        self.data_path = data_path
        self.phase = phase
        self.augment = augment
        self.img_size = img_size

        self.items = [filename.split('.')[0] for filename in os.listdir(f'{data_path}/{phase}/image')]
        
        # TODO: implement augmentations (3.5 points)
        if augment:
            # TODO:
            # Random resize
            # Random crop (within image borders, output size = img_size)
            # Random rotation
            # Random horizontal and vertical Flip
            # Random color augmentation
            transform = A.Compose([
                # A.RandomScale(0.2, p=0.8),
                # A.RandomCrop(height=self.img_size, width=self.img_size),
                A.RandomResizedCrop(self.img_size, self.img_size, [0.7, 1.3]), 
                A.Rotate(limit=180, p = 0.5),
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5),
                A.ColorJitter(p=0.5),
            ])
            self.transform = transform

        else:
        	# TODO: random crop to img_size
            self.transform = A.RandomCrop(height=self.img_size, width=self.img_size)
        
        self.to_tensor = ToTensor()

    def __len__(self):
        return len(self.items)

    def __getitem__(self, index):
        image = np.asarray(Image.open(f'{self.data_path}/{self.phase}/image/{self.items[index]}.jpg'))
        mask = np.asarray(Image.open(f'{self.data_path}/{self.phase}/mask/{self.items[index]}.png'))
        
        if self.phase == 'train':
        	# TODO: apply transform to both image and mask (0.5 points)
            transformed = self.transform(image=image, mask=mask)
            image = transformed['image']
            mask = transformed['mask']
        
        image = self.to_tensor(image.copy())
        mask = torch.from_numpy(mask.copy()).long()

        if self.phase == 'train':
            assert isinstance(image, torch.FloatTensor) and image.shape == (3, self.img_size, self.img_size)
            assert isinstance(mask, torch.LongTensor) and mask.shape == (self.img_size, self.img_size)

        return image, mask

"""### `model`
**TODO: Implement the required models.**

Typically, all segmentation networks consist of an encoder and decoder. Below is a scheme for a popular DeepLab v3 architecture:

<img src="https://i.imgur.com/cdlkxvp.png" />

The encoder consists of a convolutional backbone, typically with extensive use of convs with dilations (atrous convs) and a head, which helps to further boost the receptive field. As you can see, the general idea for the encoders is to have as big of a receptive field, as possible.

The decoder either does upsampling with convolutions (similarly to the scheme above, or to UNets), or even by simply interpolating the outputs of the encoder.

In this assignment, you will need to implement **UNet** and **DeepLab** models. Example UNet looks like this:

<img src="https://i.imgur.com/uVdcE4e.png" />

For **DeepLab** model we will have three variants for backbones: **ResNet18**, **VGG11 (with BatchNorm)**, and **MobileNet v3 (small).** Use `torchvision.models` to obtain pre-trained versions of these backbones and simply extract their convolutional parts. To familiarize yourself with **MobileNet v3** model, follow this [link](https://paperswithcode.com/paper/searching-for-mobilenetv3).

We will also use **Atrous Spatial Pyramid Pooling (ASPP)** head. Its scheme can be seen in the DeepLab v3 architecture above. ASPP is one of the blocks which greatly increases the spatial size of the model, and hence boosts the model's performance. For more details, you can refer to this [link](https://paperswithcode.com/method/aspp).
"""

import torch
from torch import nn
from torch.nn import functional as F
from torchvision import models


class Conv(nn.Module):
    """First arrow, 2 conv 3x3 ReLU"""

    def __init__(self, in_channels, out_channels, is_dropout=False):
        super().__init__()
        self.conv = nn.Sequential(
            nn.Dropout2d() if is_dropout else nn.Identity(), 
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_channels),
            nn.ReLU()
        )

    def forward(self, x):
        return self.conv(x)


class UNet(nn.Module):
    """
    TODO: 8 points

    A standard UNet network (with padding in covs).

    For reference, see the scheme in materials/unet.png
    - Use batch norm between conv and relu
    - Use max pooling for downsampling
    - Use conv transpose with kernel size = 3, stride = 2, padding = 1, and output padding = 1 for upsampling
    - Use 0.5 dropout after concat

    Args:
      - num_classes: number of output classes
      - min_channels: minimum number of channels in conv layers
      - max_channels: number of channels in the bottleneck block
      - num_down_blocks: number of blocks which end with downsampling

    The full architecture includes downsampling blocks, a bottleneck block and upsampling blocks

    You also need to account for inputs which size does not divide 2**num_down_blocks:
    interpolate them before feeding into the blocks to the nearest size which divides 2**num_down_blocks,
    and interpolate output logits back to the original shape
    """
    def __init__(self, 
                 num_classes,
                 min_channels=32,
                 max_channels=512, 
                 num_down_blocks=4):
        super(UNet, self).__init__()
        self.num_classes = num_classes
        # TODO
        self.n_min_channels = min_channels
        self.n_max_channels = max_channels
        self.num_down_blocks = num_down_blocks


        self.input_layer = Conv(3, min_channels)
        self.down_layers = nn.ModuleList([])
        self.up_layers = nn.ModuleList([])
        self.right_layers = nn.ModuleList([])
        self.number_channels = [min_channels]
        for num_layer in range(self.num_down_blocks):
            current_num_channels = self.number_channels[-1]
            next_num_channels = min(current_num_channels * 2, max_channels)
            down = nn.Sequential(nn.MaxPool2d(2, 2), Conv(current_num_channels, next_num_channels))
            self.down_layers.append(down)
            self.number_channels.append(next_num_channels)

        for num_layer in range(self.num_down_blocks):
            current_num_channels = self.number_channels[-num_layer-1]
            next_num_channels = self.number_channels[-num_layer-2]
            up = nn.ConvTranspose2d(current_num_channels, next_num_channels, 3, 2, 1, 1)
            right = Conv(current_num_channels, next_num_channels, True)

            self.up_layers.append(up)
            self.right_layers.append(right)

        self.output_layer = nn.Sequential(nn.Conv2d(self.number_channels[0], num_classes, 1), nn.Sigmoid())
        self.dropout = nn.Dropout2d(p=0.5)
    def forward(self, inputs):
        # print(f'inputs shape {inputs.shape}')
        interpolation_size = (max(round(inputs.shape[2] / (2 ** self.num_down_blocks)), 1) * (2 ** self.num_down_blocks), max(round(inputs.shape[3] / (2 ** self.num_down_blocks)), 1) * (2 ** self.num_down_blocks))
        x = F.interpolate(inputs, interpolation_size)
        # print(f'inputs shape  after interpolation {x.shape}')

        x = self.input_layer(x)
        xs = [x]
        for down in self.down_layers:
            x = down(x).clone()
            xs.append(x)
        
        # x1 = self.input_layer(x)
        # x2 = self.down1(x1)
        # x3 = self.down2(x2)
        # x4 = self.down3(x3)

        out = xs[-1].clone()
        for num in range(self.num_down_blocks):
            up = self.up_layers[num]
            right  =self.right_layers[num]
            out = up(out)
            out = torch.cat([xs[-num-2],  out], 1)
            out = self.dropout(out)
            out = right(out)

        out = self.output_layer(out)

        # print(f'outputs shape before interpolation {out.shape}')

        logits = F.interpolate(out, (inputs.shape[2], inputs.shape[3]))
        # print(f'outputs shape after interpolation {logits.shape}')

        assert logits.shape == (inputs.shape[0], self.num_classes, inputs.shape[2], inputs.shape[3]), 'Wrong shape of the logits'
        return logits


class DeepLab(nn.Module):
    """
    TODO: 6 points

    (simplified) DeepLab segmentation network.
    
    Args:
      - backbone: ['resnet18', 'vgg11_bn', 'mobilenet_v3_small'],
      - aspp: use aspp module
      - num classes: num output classes

    During forward pass:
      - Pass inputs through the backbone to obtain features
      - Apply ASPP (if needed)
      - Apply head
      - Upsample logits back to the shape of the inputs
    """
    def __init__(self, backbone, aspp, num_classes):
        super(DeepLab, self).__init__()
        self.backbone = backbone
        self.num_classes = num_classes
        self.init_backbone()

        if aspp:
            self.aspp = ASPP(self.out_features, 256, [12, 24, 36])
        else:
            self.aspp = False

        self.head = DeepLabHead(self.out_features, num_classes)

    def init_backbone(self):
        # TODO: initialize an ImageNet-pretrained backbone
        if self.backbone == 'resnet18':
            self.backbone_model = torch.nn.Sequential(*(list(models.resnet18(pretrained=True).children())[:-2]))
            self.out_features = 512 # TODO: number of output features in the backbone

        elif self.backbone == 'vgg11_bn':
            self.backbone_model = models.vgg11_bn(pretrained=True).features
            self.out_features = 512 # TODO

        elif self.backbone == 'mobilenet_v3_small':
            self.backbone_model = models.mobilenet_v3_small(pretrained=True).features
            self.out_features = 576 # TODO
        for param in self.backbone_model.parameters():
            param.requires_grad = False

    def _forward(self, x):
        # TODO: forward pass through the backbone
        if self.backbone == 'resnet18':
            pass

        elif self.backbone == 'vgg11_bn':
            pass

        elif self.backbone == 'mobilenet_v3_small':
            pass
        x = self.backbone_model(x)
        return x

    def forward(self, inputs):
        logits = self._forward(inputs)
        if self.aspp:
            logits = self.aspp(logits)
        logits = self.head(logits)
        logits = F.interpolate(logits, (inputs.shape[2], inputs.shape[3]))
        assert logits.shape == (inputs.shape[0], self.num_classes, inputs.shape[2], inputs.shape[3]), 'Wrong shape of the logits'
        return logits


class DeepLabHead(nn.Sequential):
    def __init__(self, in_channels, num_classes):
        super(DeepLabHead, self).__init__(
            nn.Conv2d(in_channels, in_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(in_channels),
            nn.ReLU(),
            nn.Conv2d(in_channels, num_classes, 1)
        )

class ConvBlock(nn.Sequential):
    def __init__(self, in_channels, num_channels, kernel_size, padding=1, dilation=1):
        super(ConvBlock, self).__init__(
            nn.Conv2d(in_channels, num_channels, kernel_size, padding=padding, dilation=dilation),
            nn.BatchNorm2d(num_channels),
            nn.ReLU()
        )


class ASPP(nn.Module):
    """
    TODO: 8 points

    Atrous Spatial Pyramid Pooling module
    with given atrous_rates and out_channels for each head
    Description: https://paperswithcode.com/method/aspp
    
    Detailed scheme: materials/deeplabv3.png
      - "Rates" are defined by atrous_rates
      - "Conv" denotes a Conv-BN-ReLU block
      - "Image pooling" denotes a global average pooling, followed by a 1x1 "conv" block and bilinear upsampling
      - The last layer of ASPP block should be Dropout with p = 0.5

    Args:
      - in_channels: number of input and output channels
      - num_channels: number of output channels in each intermediate "conv" block
      - atrous_rates: a list with dilation values
    """
    def __init__(self, in_channels, num_channels, atrous_rates):
        super(ASPP, self).__init__()
        self.convs = nn.ModuleList([ConvBlock(in_channels, num_channels, 1, 0)])
        for dilation in atrous_rates:
            self.convs.append(ConvBlock(in_channels, num_channels, 3, dilation, dilation))
        self.pooling = nn.Sequential(nn.AdaptiveAvgPool2d(1), 
                                     ConvBlock(in_channels, num_channels, 1)
                                )
        self.dropout = nn.Dropout2d(p=0.5)
        self.last_layer = ConvBlock((len(atrous_rates) + 2) * num_channels, in_channels, 1, 0)

    def forward(self, x):
        # TODO: forward pass through the ASPP module
        res = self.pooling(x)
        res = F.interpolate(res, (x.shape[2], x.shape[3]), mode='bilinear')

        for conv in self.convs:
            res = torch.cat([conv(x), res], 1)
        res = self.last_layer(res)
        res = self.dropout(res)
        assert res.shape[1] == x.shape[1], 'Wrong number of output channels'
        assert res.shape[2] == x.shape[2] and res.shape[3] == x.shape[3], 'Wrong spatial size'
        return res

"""### `loss`
**TODO: implement test losses.**

For validation, we will use three metrics. 
- Mean intersection over union: **mIoU**,
- Mean class accuracy: **classAcc**,
- Accuracy: **Acc**.

To calculate **IoU**, use this formula for binary segmentation masks for each class, and then average w.r.t. all classes:

$$ \text{IoU} = \frac{ \text{area of intersection} }{ \text{area of union} } = \frac{ \| \hat{m} \cap m  \| }{ \| \hat{m} \cup m \| }, \quad \text{$\hat{m}$ — predicted binary mask},\ \text{$m$ — target binary mask}.$$

Generally, we want our models to optimize accuracy since this implies that it makes little mistakes. However, most of the segmentation problems have imbalanced classes, and therefore the models tend to underfit the rare classes. Therefore, we also need to measure the mean performance of the model across all classes (mean IoU or mean class accuracy). In reality, these metrics (not the accuracy) are the go-to benchmarks for segmentation models.
"""

def calc_val_data(preds, masks, num_classes):
    # print(f'masks shape {masks.shape}')

    # print(f'preds shape in validation before argmax {preds.shape}')
    preds = torch.argmax(preds, dim=1)
    preds = F.one_hot(preds, num_classes).permute((0,3, 1, 2)) 
    masks = F.one_hot(masks, num_classes).permute((0,3, 1, 2)) 
    # print(f'preds shape in validation after argmax {preds.shape}')
    
    intersection = torch.sum(preds * masks, dim=(2,3)) # TODO: calc intersection for each class
    union = torch.sum(preds + masks, dim=(2,3)) # TODO: calc union for each class
    target = torch.sum(masks, dim=(2,3)) # TODO: calc number of pixels in groundtruth mask per class
    # Output shapes: B x num_classes

    assert isinstance(intersection, torch.Tensor), 'Output should be a tensor'
    assert isinstance(union, torch.Tensor), 'Output should be a tensor'
    assert isinstance(target, torch.Tensor), 'Output should be a tensor'

    assert intersection.shape == union.shape == target.shape, 'Wrong output shape'
    assert union.shape[0] == masks.shape[0] and union.shape[1] == num_classes, 'Wrong output shape'

    return intersection, union, target

def calc_val_loss(intersection, union, target, eps = 1e-7):
    mean_iou = torch.mean((intersection + eps) / (union + eps), dim=1) # TODO: calc mean class iou
    mean_class_rec = torch.mean((intersection+eps) / (target+eps), dim=1) # TODO: calc mean class recall
    mean_acc = torch.sum((intersection +eps), dim=1)/ torch.sum((target+eps), dim=1) # TODO: calc mean accuracy

    return mean_iou, mean_class_rec, mean_acc

"""### `train`
**TODO: define optimizer and learning rate scheduler.**

You need to experiment with different optimizers and schedulers and pick one of each which works the best. Since the grading will be partially based on the validation performance of your models, we strongly advise doing some preliminary experiments and pick the configuration with the best results.
"""

# Copyright The PyTorch Lightning team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Modifications Copyright Skoltech Deep Learning Course.

import torch
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader

# from .model import UNet, DeepLab
# from .dataset import FloodNet
# from . import loss



class SegModel(pl.LightningModule):
    def __init__(
        self,
        model: str,
        backbone: str,
        aspp: bool,
        augment_data: bool,
        optimizer: dict = {'Adam' :{'lr' :1e-3}},
        scheduler: dict = {'StepLR' : {'step_size' :10, 'gamma' : 0.5}},
        lr: float = 1e-3,
        batch_size: int = 16,
        data_path: str = 'datasets/tiny-floodnet-challenge',
        image_size: int = 256,
    ):
        super(SegModel, self).__init__()
        self.num_classes = 8
        model = model.lower()
        if model == 'unet':
            self.net = UNet(self.num_classes)
        elif model == 'deeplab':
            self.net = DeepLab(backbone, aspp, self.num_classes)

        self.train_dataset = FloodNet(data_path, 'train', augment_data, image_size)
        self.test_dataset = FloodNet(data_path, 'test', augment_data, image_size)

        self.batch_size = batch_size
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.lr = lr
        self.eps = 1e-7

        # Visualization
        self.color_map = torch.FloatTensor(
            [[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1],
             [1, 0, 0], [1, 0, 1], [1, 1, 0], [1, 1, 1]])

    def forward(self, x):
        return self.net(x)

    def training_step(self, batch, batch_idx):
        img, mask = batch
        pred = self.forward(img)

        train_loss = F.cross_entropy(pred, mask)

        self.log('train_loss', train_loss, prog_bar=True)

        return train_loss

    def validation_step(self, batch, batch_idx):
        img, mask = batch
        pred = self.forward(img)

        intersection, union, target = calc_val_data(pred, mask, self.num_classes)

        return {'intersection': intersection, 'union': union, 'target': target, 'img': img, 'pred': pred, 'mask': mask}

    def validation_epoch_end(self, outputs):
        intersection = torch.cat([x['intersection'] for x in outputs])
        union = torch.cat([x['union'] for x in outputs])
        target = torch.cat([x['target'] for x in outputs])

        mean_iou, mean_class_rec, mean_acc = calc_val_loss(intersection, union, target, self.eps)

        log_dict = {'mean_iou': mean_iou, 'mean_class_rec': mean_class_rec, 'mean_acc': mean_acc}

        for k, v in log_dict.items():
            self.log(k, v, prog_bar=True)

        # Visualize results
        img = torch.cat([x['img'] for x in outputs]).cpu()
        pred = torch.cat([x['pred'] for x in outputs]).cpu()
        mask = torch.cat([x['mask'] for x in outputs]).cpu()

        pred_vis = self.visualize_mask(torch.argmax(pred, dim=1))
        mask_vis = self.visualize_mask(mask)

        results = torch.cat(torch.cat([img, pred_vis, mask_vis], dim=3).split(1, dim=0), dim=2)
        results_thumbnail = F.interpolate(results, scale_factor=0.25, mode='bilinear')[0]

        self.logger.experiment.add_image('results', results_thumbnail, self.current_epoch)

    def visualize_mask(self, mask):
        b, h, w = mask.shape
        mask_ = mask.view(-1)

        if self.color_map.device != mask.device:
            self.color_map = self.color_map.to(mask.device)

        mask_vis = self.color_map[mask_].view(b, h, w, 3).permute(0, 3, 1, 2).clone()

        return mask_vis

    def configure_optimizers(self):
        # TODO: 2 points
        # Use self.optimizer and self.scheduler to call different optimizers
        name_opt = next(iter(self.optimizer.keys()))
        opt_parameters = self.optimizer[name_opt]
        if name_opt=='Adam':
            opt = torch.optim.Adam(self.net.parameters(), **opt_parameters) # TODO: init optimizer
        elif name_opt=='SGD':
            opt = torch.optim.SGD(self.net.parameters(), **opt_parameters)
        else:
            raise NotImplementedError

        name_sch = next(iter(self.scheduler.keys()))
        sch_parameters = self.scheduler[name_sch]

        if name_sch == 'StepLR':
            sch = torch.optim.lr_scheduler.StepLR(opt, **sch_parameters) # TODO: init learning rate scheduler
        else:
            raise NotImplementedError
        return [opt], [sch]

    def train_dataloader(self):
        return DataLoader(self.train_dataset, num_workers=2, batch_size=self.batch_size, shuffle=True)

    def val_dataloader(self):
        return DataLoader(self.test_dataset, num_workers=2, batch_size=1, shuffle=False)

"""## Part 2. Train and benchmark

In this part of the assignment, you need to train the following models and measure their training time:
- **UNet** (with and without data augmentation),
- **DeepLab** with **ResNet18** backbone (with **ASPP** = True and False),
- **DeepLab** with the remaining backbones you implemented and **ASPP** = True).

To get the full mark for this assignment, all the required models should be trained (and their checkpoints provided), and have at least 0.5 accuracies.

After the models are trained, evaluate their inference time on both GPU and CPU.

Example training and evaluation code are below.
"""

import pytorch_lightning as pl
# from semantic_segmentation.train import SegModel
import time
import torch


def define_model(model_name: str, 
                 backbone: str, 
                 aspp: bool, 
                 augment_data: bool, 
                 optimizer: dict, 
                 scheduler: dict, 
                 lr: float, 
                 checkpoint_name: str = '', 
                 batch_size: int = 16):
    # assignment_dir = 'semantic_segmentation'
    assignment_dir = '/content/drive/MyDrive/Skoltech/DL/HW2/report/15_04'

    experiment_name = f'{model_name}_{backbone}_augment={augment_data}_aspp={aspp}'#_opt={optimizer}_sch={scheduler}'
    model_name = model_name.lower()
    backbone = backbone.lower() if backbone is not None else backbone
    
    model = SegModel(
        model_name, 
        backbone, 
        aspp, 
        augment_data,
        optimizer,
        scheduler,
        lr,
        batch_size, 
        data_path='datasets/tiny-floodnet-challenge', 
        image_size=256)

    if checkpoint_name:
        model.load_state_dict(torch.load(f'{assignment_dir}/{experiment_name}/{checkpoint_name}')['state_dict'])
    
    return model, experiment_name

def train(model, experiment_name, use_gpu):
    # assignment_dir = 'semantic_segmentation'
    assignment_dir = '/content/drive/MyDrive/Skoltech/DL/HW2/report/15_04'
    logger = pl.loggers.TensorBoardLogger(save_dir=f'{assignment_dir}', name=experiment_name)

    checkpoint_callback = pl.callbacks.ModelCheckpoint(
        monitor='mean_iou',
        dirpath=f'{assignment_dir}/{experiment_name}',
        filename='{epoch:02d}-{mean_iou:.3f}',
        mode='max')
    
    trainer = pl.Trainer(
        max_epochs=100, 
        gpus=1 if use_gpu else None, 
        benchmark=True, 
        check_val_every_n_epoch=5, 
        logger=logger, 
        callbacks=[checkpoint_callback])

    time_start = time.time()
    
    trainer.fit(model)
    
    torch.cuda.synchronize()
    time_end = time.time()
    
    training_time = (time_end - time_start) / 60
    
    return training_time

model, experiment_name = define_model(
    model_name='DeepLab',
    backbone='MobileNet_v3_small',
    aspp=True,
    augment_data=True,
    optimizer={'Adam' : {'lr' : 1e-3, 'weight_decay' : 1e-4}}, # use these options to experiment
    scheduler={'StepLR': {'step_size' : 10, 'gamma' :0.5}}, # with optimizers and schedulers
    lr=1e-3,
    batch_size=16) # experiment to find the best LR
training_time = train(model, experiment_name, use_gpu=True)

print(f'Training time: {training_time:.3f} minutes')
np.savetxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_MobileNet_v3_small_augment=True_aspp=True_time.txt', [training_time])

"""After training, the loss curves and validation images with their segmentation masks can be viewed using the TensorBoard extension:"""

# # !kill 2534
# %load_ext tensorboard
# %tensorboard --logdir semantic_segmentation/logs --host 0.0.0.0

# Commented out IPython magic to ensure Python compatibility.
# !kill 2534
# %load_ext tensorboard
# %tensorboard --logdir /content/drive/MyDrive/Skoltech/DL/HW2/report/15_04 --host 0.0.0.0

"""Inference time can be measured via the following function:"""

def calc_inference_time(model, device, input_shape=(1000, 750), num_iters=100):
    timings = []

    for i in range(num_iters):
        x = torch.randn(1, 3, *input_shape).to(device)
        time_start = time.time()
        
        model(x)
        
        torch.cuda.synchronize()
        time_end = time.time()
        
        timings.append(time_end - time_start)

    return sum(timings) / len(timings) * 1e3


model = define_model(
    model_name='deeplab',
    backbone='vgg11_bn',
    aspp=True,
    augment_data=True,
    optimizer={'Adam' : {'lr' : 1e-1, 'weight_decay' : 1e-4}}, # use these options to experiment
    scheduler={'StepLR': {'step_size' : 10, 'gamma' :0.2}}, # with optimizers and schedulers
    lr = 1e-3,
    batch_size=16,
    checkpoint_name='epoch=19-mean_iou=0.392.ckpt')

# inference_time = calc_inference_time(model.eval().cpu(), 'cpu')
inference_time = calc_inference_time(model[0].eval().cuda(), 'cuda')

print(f'Inferece time (per frame): {inference_time:.3f} ms')

Unet_inference_time = 87.750
DeepLab_Mobile_inference_time = 14.917
DeepLab_ResNet_inference_time = 17.880
DeepLab_VGG_inference_time = 54.159

Unet_training_time = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/UNet_time.txt')
DeepLab_Mobile_training_time = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_MobileNet_v3_small_augment=True_aspp=True_time.txt')
DeepLab_ResNet_training_time = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_ResNet18_augment=True_aspp=True_time.txt')
DeepLab_VGG_training_time = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_VGG11_bn_augment=True_aspp=True_time.txt')

Unet_size = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/UNet_size.txt')
DeepLab_Mobile_size = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_MobileNet_v3_small_size_aspp=True.txt')
DeepLab_ResNet_size = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_ResNet18_size_aspp=True.txt')
DeepLab_VGG_size = np.loadtxt('/content/drive/MyDrive/Skoltech/DL/HW2/report/16_04/DeepLab_VGG11_bn_size_aspp=True.txt')

"""Your trained weights are available in the `part1_semantic_segmentation/logs` folder. Inside, your experiment directory has a log file with the following mask: `{epoch:02d}-{mean_iou:.3f}.ckpt`. <font color='red'>**Make sure that you models satisfy the accuracy requirements, upload them to your personal Google Drive, and provide a link to google drive folder**."""

checkpoint_names = {
    'UNet_None_augment=False_aspp=None.ckpt',
    'UNet_None_augment=True_aspp=None.ckpt',
    'DeepLab_ResNet18_augment=True_aspp=False.ckpt',
    'DeepLab_ResNet18_augment=True_aspp=True.ckpt',
    'DeepLab_VGG11_bn_augment=True_aspp=True.ckpt',
    'DeepLab_MobileNet_v3_small_augment=True_aspp=True.ckpt',
}

"""## Part 3. Report

You should have obtained 7 different models, which we will use for the comparison and evaluation. When asked to visualize specific loss curves, simply configure these plots in TensorBoard, screenshot, store them in the `report` folder, and load into Jupyter markdown:

`<img src="./part1_semantic_segmentation/report/<screenshot_filename>"/>`

If you have problems loading these images, try uploading them [here](https://imgur.com) and using a link as `src`. Do not forget to include the raw files in the `report` folder anyways.

You should make sure that your plots satisfy the following requirements:
- Each plot has a title,
- If there are multiple curves on one plot (or dots on the scatter plot), the plot legend should also be present,
- If the plot is not obtained using TensorBoard (Task 3), the axis should have names and ticks.

<font color='red'>**In this task, it is obligatory to provide accuracy plots on the training and validation datasets obtained during training, as well as examples of the work of each of the models on the images. Without plots, your work will get 0 points. Writing a report is just as important as writing code.**</font>

#### Task 1.
Visualize training loss and validation loss curves for UNet trained with and without data augmentation. What are the differences in the behavior of these curves between these experiments, and what are the reasons?

![](https://drive.google.com/uc?export=view&id=1Pbal4tgJ-oJdn5bdlre7lFByG2_jXMhH)

![](https://drive.google.com/uc?export=view&id=1k14OGfZ4ZuX-QAFnONLVr9aFeE-iH1Ft)

![](https://drive.google.com/uc?export=view&id=1M8eSoppnJiU191YFztu_b801SADB_PYE)

As we can see training loss for augmented higher, but validation metrics better. It is expected, since augmentation used as regularization technique dedicated to impove generalization ability and stability.

#### Task 2.
Visualize training and validation loss curves for ResNet18 trained with and without ASPP. Which model performs better?

![](https://drive.google.com/uc?export=view&id=1dcP7GmeSeLDdBuxh9vuK9O6HgZVHWUIO)

![](https://drive.google.com/uc?export=view&id=1piVRJI0d-rJZfCYrqbtHSenRKKMFTlHX)

![](https://drive.google.com/uc?export=view&id=1bKkmojdf6Z2MTytesgRGEi9vh-cfVRdt)

In terms of accuracy ResNet with ASPP performs better, but IOU is lower.

#### Task 3.
Compare **UNet** with augmentations and **DeepLab** with all backbones (only experiments with **ASPP**). To do that, put these models on three scatter plots. For the first plot, the x-axis is **training time** (in minutes), for the second plot, the x-axis is **inference time** (in milliseconds), and for the third plot, the x-axis is **model size** (in megabytes). The size of each model is printed by PyTorch Lightning. For all plots, the y-axis is the best **mIoU**. To clarify, each of the **4** requested models should be a single dot on each of these plots.

Which models are the most efficient with respect to each metric on the x-axes? For each of the evaluated models, rate its performance using their validation metrics, training and inference time, and model size. Also for each model explain what are its advantages, and how its performance could be improved?
"""

Unet_iou = 0.396
DeepLab_Mobile_iou = 0.398
DeepLab_ResNet_iou = 0.375
DeepLab_VGG_iou = 0.392

import matplotlib.pyplot as plt
fig, axes = plt.subplots(ncols=3, figsize=(20, 4))

axes[0].scatter([Unet_training_time], [Unet_iou], label='Unet')
axes[0].scatter([DeepLab_Mobile_training_time], [DeepLab_Mobile_iou], label='DeepLab Mobile')
axes[0].scatter([DeepLab_ResNet_training_time], [DeepLab_ResNet_iou], label='DeepLab ResNet')
axes[0].scatter([DeepLab_VGG_training_time], [DeepLab_VGG_iou], label='DeepLab VGG')
axes[0].legend()
axes[0].set_title('Training time vs IOU')
axes[0].set_xlabel('Training time, min')
axes[0].set_ylabel('IOU')


axes[1].scatter([Unet_inference_time], [Unet_iou], label='Unet')
axes[1].scatter([DeepLab_Mobile_inference_time], [DeepLab_Mobile_iou], label='DeepLab Mobile')
axes[1].scatter([DeepLab_ResNet_inference_time], [DeepLab_ResNet_iou], label='DeepLab ResNet')
axes[1].scatter([DeepLab_VGG_inference_time], [DeepLab_VGG_iou], label='DeepLab VGG')
axes[1].legend()
axes[1].set_title('Inference time vs IOU')
axes[1].set_xlabel('Inference time, ms')
axes[1].set_ylabel('IOU')


axes[2].scatter([Unet_size], [Unet_iou], label='Unet')
axes[2].scatter([DeepLab_Mobile_size[-1]], [DeepLab_Mobile_iou], label='DeepLab Mobile')
axes[2].scatter([DeepLab_ResNet_size[-1]], [DeepLab_ResNet_iou], label='DeepLab ResNet')
axes[2].scatter([DeepLab_VGG_size[-1]], [DeepLab_VGG_iou], label='DeepLab VGG')
axes[2].legend()
axes[2].set_title('Size Model vs IOU')
axes[2].set_xlabel('Size Model, M')
axes[2].set_ylabel('IOU')
plt.show()

"""In terms of IOU the best is DeepLab with Mobile backbone.

In terms of training time the best is DeepLab with Mobile backbone.

In terms of inference time the best is DeepLab with Mobile backbone.

In terms of size model the best is UNet but DeepLab with Mobile backbone is very close. 

According to all metrics, time and size the best obtained model is DeepLab with Mobile backbone. DeepLab with ResNet backbone has noticeable lower IOU qiality and UNet and  DeepLab with VGG backbone have far more parameters and train longer.

#### Task 4.

Pick the best model according to **mIoU** and look at the visualized predictions on the validation set in the TensorBoard. For each segmentation class, find the good examples (if they are available), and the failure cases. Provide the zoomed-in examples and their analysis below. Please do not attach full validation images, only the areas of interest which you should crop manually.
"""

# code for displaying multiple images in one figure
  
import cv2
from matplotlib import pyplot as plt
def display_images(image1, image2, image3):
    fig = plt.figure(figsize=(10, 7))
    
    rows = 3
    columns = 1
    
    BadImage1 = cv2.imread(image1)
    BadImage2 = cv2.imread(image2)
    BadImage3 = cv2.imread(image3)

    fig.add_subplot(rows, columns, 1)
    plt.imshow(BadImage1)
    plt.axis('off')
    
    fig.add_subplot(rows, columns, 2)
    plt.imshow(BadImage2)
    plt.axis('off')
    
    fig.add_subplot(rows, columns, 3)
    plt.imshow(BadImage3)
    plt.axis('off')
    plt.show()

"""### Bad Images"""

display_images("BadImage1.png", "BadImage2.png", "BadImage3.png")

"""As we can see, the model shows poor quality when there are many classes in segmentation mask, especially if they are grain-like, closely stationed."""

display_images("GoodImage1.png", "GoodImage2.png", "GoodImage3.png")

"""The model performs good, when there are large clusters of same classes without mixing.

**<font color='red'>Before the submission please convert your notebook to .py file and check that it runs correctly. How to get .py file in Colab: File -> Download -> Download .py**
Left side menu in Colab -> Files -> Upload your script
and then check.
"""

# !python "/content/копия_блокнота__hw2_semantic_segmentation_surname_name_attempt_1_ipynb_ (3).py"

"""You can replace TODO strings to None"""